#define INTEGRATED_ARENA_MATCHING
#define INDUN_TIME
#define INDUN_COUNT_ITEM
using System;

public enum PACKET_CATEGORY : byte
{
	_CATEGORY_CL  = 1,
	_CATEGORY_CS  = 2,
	_CATEGORY_CG  = 3,
	_CATEGORY_CS2 = 4,
	_CATEGORY_CI  = 5,
	_CATEGORY_CS3 = 6,
	_CATEGORY_DUMMY,
	NUM_CATEGORY = _CATEGORY_DUMMY - 1
}

public enum eRESULTCODE : int
{
	eRESULT_NOTHING = -1,

	//all
	eRESULT_SUCC,
	eRESULT_SUCC_REENTRANCE,
	eRESULT_FAIL,

	//system
	eRESULT_FAIL_DIS_DBAGENT,
	eRESULT_FAIL_DIS_GAMESERVER,

	//channel
	eRESULT_FAIL_CHANNEL_INVALID,
	eRESULT_FAIL_CHANNEL_FULL,
	eRESULT_FAIL_CHANNEL_COMBAT,
	eRESULT_FAIL_CHANNEL_USING_CONTENT,

	//
	eRESULT_FAIL_RETURN_CHARSELECT_WAIT,

	//login
	eRESULT_FAIL_VERSION,
	eRESULT_FAIL_ACCOUNT_DUPLICATE,
	eRESULT_FAIL_WITHDRAWAL_ONEDAY,
	eRESULT_FAIL_BAN_LOGIN,
	eRESULT_FAIL_GM_EDIT,
	eRESULT_FAIL_ACCOUNT_DELETED,

	//character create
	eRESULT_FAIL_CHAR_CREATE,
	eRESULT_FAIL_CHAR_CREATE_BLOCK,
	eRESULT_FAIL_NAME,
	eRESULT_FAIL_SLOT_OVER,
	eRESULT_FAIL_COLLISION_NAME,
	eRESULT_FAIL_SERVERLIMITOVER,

	//character delete
	eRESULT_FAIL_CHAR_DELETE_GUILDMASTER,
	eRESULT_FAIL_CHAR_DELETE_MONTHCOUNTOVER,

	//subtitle
	eRESULT_FAIL_SUBTITLE_SET_NOTHING,
	eRESULT_FAIL_SUBTITLE_SET_ALREADY,
	#region -DelegateImage
	eRESULT_FAIL_IMAGE_SET_NOTHING,
	eRESULT_FAIL_IMAGE_BUY_ALREADY,
	eRESULT_FAIL_IMAGE_BUY_NEED_GOLD,
	eRESULT_FAIL_IMAGE_BUY_NEED_CASH,
	#endregion

	//move / skill
	eRESULT_FAIL_MOVE,

	//warp
	eRESULT_FAIL_WARP,

	//item
	eRESULT_FAIL_BAD_ITEM,
	eRESULT_FAIL_IVNENTORY_FULL,

	//item use
	eRESULT_FAIL_ITEM_USE_SKILLRESET_DEFAULT,
	eRESULT_FAIL_ITEM_USE_NPC_SPAWN,

	eRESULT_FAIL_ITEM_USE,
	eRESULT_FAIL_ITEM_USE_AREA,
	eRESULT_FAIL_ITEM_USE_ALREADY_AREA,
	eRESULT_FAIL_ITEM_USE_NOT_EXIST_TARGET,
	eRESULT_FAIL_ITEM_USE_BAD_TARGET,
	eRESULT_FAIL_ITEM_USE_ALREADY_TARGET,
	

	//item pickup
	eRESULT_FAIL_PICKUP_DROPITEM,

	//item strength
	eRESULT_ITEM_STRENGTHEN_SUCCESS,
	eRESULT_ITEM_STRENGTHEN_FAIL,
	eRESULT_ITEM_STRENGTHEN_FAIL_PROTECT,

	//item enchant
	eRESULT_ITEM_ENCHANT_SUCCESS,
	eRESULT_ITEM_ENCHANT_FAIL,
	eRESULT_ITEM_ENCHANT_FAIL_PROTECT,

	//item mix
	eRESULT_ITEM_MIX_COS_FAIL,
	eRESULT_ITEM_MIX_OVER_MAX,

	//storage
	eRESULT_FAIL_STORAGE,
	eRESULT_FAIL_STORAGE_FULL,
	eRESULT_FAIL_STORAGE_UP_MAX_COUNT,
	eRESULT_FAIL_STORAGE_UP_NEED_GOLD,

	//product
	eRESULT_FAIL_PRODUCT_SCRIPT,
	eRESULT_FAIL_PRODUCT_INVAILD_TECH,
	eRESULT_FAIL_PRODUCT_TECH_REGISTER,
	eRESULT_FAIL_PRODUCT_SLOT,
	eRESULT_FAIL_PRODUCT_ADD_SLOT,
	eRESULT_FAIL_PRODUCT_CASH_LEVEL_UP,
	eRESULT_FAIL_PRODUCT_MATERIAL_LACK,
	eRESULT_FAIL_PRODUCT_GOLD_LACK,

	//quest start
	eRESULT_FAIL_QUEST_START,
	eRESULT_FAIL_QUEST_ALREADY_CLEAR_ONEDAY,
	eRESULT_FAIL_QUEST_IMPOSSIBLE_REPEAT,
	eRESULT_FAIL_QUEST_OVER_REPEAT,
	eRESULT_FAIL_QUEST_NEED_LEVEL,
	eRESULT_FAIL_QUEST_NEED_CLASS,
	eRESULT_FAIL_QUEST_NEED_QUEST,
	eRESULT_FAIL_QUEST_ENTER_MAP,
	eRESULT_FAIL_QUEST_ENTER_MAP_POSITION,
	eRESULT_FAIL_QUEST_GET_SKILL,
	eRESULT_FAIL_QUEST_USE_ITEM,
	eRESULT_FAIL_QUEST_TIMELIMIT,
	eRESULT_FAIL_QUEST_WARP,
	eRESULT_FAIL_QUEST_WARP_PVP_ARENA,
	eRESULT_FAIL_QUEST_WARP_COMBAT,

	eRESULT_FAIL_QUEST_FULL,
	eRESULT_FAIL_QUEST_NEED_INVENTORYSLOT,
	eRESULT_FAIL_QUEST_SUBTITLE_COUNT,
	eRESULT_FAIL_QUEST_SUBTITLE_HAVE,
	eRESULT_FAIL_QUEST_SUBTITLE_USE,
	eRESULT_FAIL_QUEST_COLLECT_HAVE_BUFF,

	//quest clear
	eRESULT_FAIL_QUEST_CLEAR,
	eRESULT_FAIL_QUEST_CLEAR_GOLD,
	eRESULT_FAIL_QUEST_CLEAR_CASH,

	//quest reward
	eRESULT_FAIL_REWARD,
	eRESULT_FAIL_REWARD_GOLD,
	eRESULT_FAIL_REWARD_EMPTYITEMSLOT,
	eRESULT_FAIL_REWARD_NO_CONDITION,

	//quest drop
	eRESULT_FAIL_DROP,

	//object
	eRESULT_FAIL_OBJECT_BAD,
	eRESULT_FAIL_OBJECT_CHARGE,
	eRESULT_FAIL_OBJECT_ALREADY_BREAK,

	//trade
	eRESULT_FAIL_TRADE_NOT,
	eRESULT_FAIL_TRADE_BADUSER,
	eRESULT_FAIL_TRADE_REFUSE,
	eRESULT_FAIL_TRADE_GAP,
	eRESULT_FAIL_TRADE_IMPOSSIBLE_ITEM,
	eRESULT_FAIL_TRADE_ALREADY_ITEM,
	eRESULT_FAIL_TRADE_EMPTY_ITEM,
	eRESULT_FAIL_TRADE_OVERGOLD,
	eRESULT_FAIL_TRADE_NOTREADY,
	eRESULT_FAIL_TRADE_INVENTORYFULL,
	eRESULT_FAIL_TRADE_OTHERNOTOK,
	eRESULT_FAIL_TRADE_LOCK,
	eRESULT_FAIL_TRADE_RESTRICT_GOLD,
	eRESULT_FAIL_TRADE_ALREADY_CANCEL,

	//party
	eRESULT_FAIL_PARTY_NOT_EXIST,
	eRESULT_FAIL_PARTY_CREATE,
	eRESULT_FAIL_PARTY_CHANGE_CAPTAIN,
	eRESULT_FAIL_PARTY_INVITE,
	eRESULT_FAIL_PARTY_INVITE_ALREADY,
	eRESULT_FAIL_PARTY_INVITE_REFUSE,
	eRESULT_FAIL_PARTY_INVITE_PLAYING,
	eRESULT_FAIL_PARTY_INVITE_BLOCKOUT,
	eRESULT_FAIL_PARTY_JOIN,
	eRESULT_FAIL_PARTY_JOIN_FULL,
	eRESULT_FAIL_PARTY_JOIN_CLOSED,
	eRESULT_FAIL_PARTY_JOIN_BLOCKOUT,
	eRESULT_FAIL_PARTY_BANNED_EXIT,
	eRESULT_FAIL_PARTY_SEARCH,	//<-- 2014.01.10.
	eRESULT_FAIL_PARTY_DICE_SHAKE,
	eRESULT_FAIL_PARTY_INDUNMATCHING,

	eRESULT_FAIL_PARTY_ARENAMATCHING,
	eRESULT_FAIL_PARTY_ARENA,
	
	eRESULT_FAIL_PARTY_WARP_CAPTAIN_MYSELF,
	eRESULT_FAIL_PARTY_WARP_CHANNEL_FULL,
	eRESULT_FAIL_PARTY_TUTORIALZONE,
	
	//skill
	eRESULT_FAIL_SKILLLEARN_NOT_EXIST,
	eRESULT_FAIL_SKILLLEARN_LEARN_ALREADY,
	eRESULT_FAIL_SKILLLEARN_LEARN_OTHER,
	eRESULT_FAIL_SKILLLEARN_NEED_LEVEL,
	eRESULT_FAIL_SKILLLEARN_NEED_SKILLLEVEL,
	eRESULT_FAIL_SKILLLEARN_NEED_GOLD,
	eRESULT_FAIL_SKILLLEARN_NEED_CLASS,

	//post
	eRESULT_FAIL_POST_NOT,
	eRESULT_FAIL_POST_SEND,
	eRESULT_FAIL_POST_SEND_BLOCKOUT,
	eRESULT_FAIL_POST_ITEM_SEND,
	eRESULT_FAIL_POST_GOLD_SEND,
	eRESULT_FAIL_POST_RECEIVER,
	eRESULT_FAIL_POST_LIST,
	eRESULT_FAIL_POST_ITEM_RECEIVE,
	eRESULT_FAIL_POST_GOLD_RECEIVE,

	//chat
	eRESULT_FAIL_CHAT_MYSELF,
	eRESULT_FAIL_CHAT_NOTHING_CHAR,
	eRESULT_FAIL_CHAT_NOTHING_PARTY,
	eRESULT_FAIL_CHAT_NOTHING_GUILD,

	//Shop
	eRESULT_FAIL_SHOP_NOT,
	eRESULT_FAIL_SHOP_IMPOSSIBLE_ITEM,
	eRESULT_FAIL_SHOP_NOTGOLD,
	eRESULT_FAIL_SHOP_NOTCASH,
	eRESULT_FAIL_SHOP_NOTSOCIALPOINT,
	eRESULT_FAIL_SHOP_GAP,
	eRESULT_FAIL_SHOP_NOTREPURCHASEITEM,
	eRESULT_FAIL_SHOP_OVERGOLD,
	eRESULT_FAIL_SHOP_INVENTORYFULL,
	eRESULT_FAIL_SHOP_MAXLIMITOVER,
	eRESULT_FAIL_SHOP_SYSTEMWAIT,
	eRESULT_FAIL_SHOP_NOGACHA,
	eRESULT_FAIL_SHOP_BUY_LIMIT,
	eRESULT_FAIL_SHOP_HAVE_NOTITEM,

	//charge
	eRESULT_FAIL_CHARGE_NOT,
	eRESULT_FAIL_CHARGE_SYSTEMWAIT,
	eRESULT_FAIL_CHARGE_MAXCASH,
	eRESULT_FAIL_CHARGE_MAXGOLD,
	eRESULT_FAIL_CHARGE_SAME_DAILY,
	eRESULT_FAIL_CHARGE_DONT_UNREGISTER,

	//PrivateShop
	eRESULT_FAIL_PRIVATESHOP_DONTCREATE,
	eRESULT_FAIL_PRIVATESHOP_NOTCREATED,
	eRESULT_FAIL_PRIVATESHOP_NOTREADY,
	eRESULT_FAIL_PRIVATESHOP_IMPOSSIBLE_ITEM,
	eRESULT_FAIL_PRIVATESHOP_ALREADY_ITEM,
	eRESULT_FAIL_PRIVATESHOP_EMPTY,
	eRESULT_FAIL_PRIVATESHOP_NOTOPEN,
	eRESULT_FAIL_PRIVATESHOP_NOT,
	eRESULT_FAIL_PRIVATESHOP_ENTER,
	eRESULT_FAIL_PRIVATESHOP_GAP,
	eRESULT_FAIL_PRIVATESHOP_NOTITEM,
	eRESULT_FAIL_PRIVATESHOP_NOTGOLD,
	eRESULT_FAIL_PRIVATESHOP_INVENTORYFULL,
	eRESULT_FAIL_PRIVATESHOP_LESS,
	eRESULT_FAIL_PRIVATESHOP_OVERGOLD,
	eRESULT_FAIL_PRIVATESHOP_NOTENTER,
	eRESULT_FAIL_PRIVATESHOP_DONTDESTORY,
	eRESULT_FAIL_PRIVATESHOP_ALREADYCREATE,
	eRESULT_FAIL_PRIVATESHOP_MANY,
	eRESULT_FAIL_PRIVATESHOP_SYSTEMWAIT_ITEMBUY,
	eRESULT_FAIL_PRIVATESHOP_SYSTEMWAIT_DESTROY,
	eRESULT_FAIL_PRIVATESHOP_SYSTEMWAIT_LOGIN,
	eRESULT_FAIL_PRIVATESHOP_SAVE_OVERCOUNT,
	eRESULT_FAIL_PRIVATESHOP_GOLD_IS_ZERO,
	eRESULT_FAIL_PRIVATESHOP_ANOTHERCHAR_OPENED,

	//waypoint
	eRESULT_FAIL_WAYPOINT_ALREADY_ACTIVE,
	eRESULT_FAIL_WAYPOINT_NOT_ACTIVE,
	eRESULT_FAIL_WAYPOINT_BAD,
	eRESULT_FAIL_WAYPOINT_BAD_GOLD,
	eRESULT_FAIL_WAYPOINT_LEVEL,

	//guild
	eRESULT_FAIL_GUILD,
	eRESULT_FAIL_GUILD_CREATE,
	eRESULT_FAIL_GUILD_EXIST,
	eRESULT_FAIL_GUILD_MAX_LEVEL,
	eRESULT_FAIL_GUILD_NEED_LEVEL,
	eRESULT_FAIL_GUILD_NEED_GOLD,
	eRESULT_FAIL_GUILD_NOT_EXIST,
	eRESULT_FAIL_GUILD_NAME_EXIST,
	eRESULT_FAIL_GUILD_INVITE,
	eRESULT_FAIL_GUILD_INVITE_NOT_EXIST,
	eRESULT_FAIL_GUILD_INVITE_REFUSE,
	eRESULT_FAIL_GUILD_INVITE_PLAYING,
	eRESULT_FAIL_GUILD_INVITE_FULL,
	eRESULT_FAIL_GUILD_INVITE_TUTORIAL,
	eRESULT_FAIL_GUILD_INVITE_PVP,
	eRESULT_FAIL_GUILD_JOIN,
	eRESULT_FAIL_GUILD_JOIN_FULL,
	eRESULT_FAIL_GUILD_JOIN_ALREADY,
	eRESULT_FAIL_GUILD_JOIN_LEVEL,
	eRESULT_FAIL_GUILD_EXIT,
	eRESULT_FAIL_GUILD_EXIT_MASTER,
	eRESULT_FAIL_GUILD_NOT_MEMBER,
	eRESULT_FAIL_GUILD_NOT_PERMISSION,
	eRESULT_FAIL_GUILD_MEMBER_INSERT,
	eRESULT_FAIL_GUILD_MEMBER_DELETE,
	eRESULT_FAIL_GUILD_SUPERVISE,
	eRESULT_FAIL_GUILD_BUSY,

//friend
	eRESULT_FAIL_FRIEND,
	eRESULT_FAIL_FRIEND_FULL,
	eRESULT_FAIL_FRIEND_NOT_EXIST,
	eRESULT_FAIL_FRIEND_INVITE,
	eRESULT_FAIL_FRIEND_INVITE_NOTHING_USER,
	eRESULT_FAIL_FRIEND_INVITE_FULL_OTHER,
	eRESULT_FAIL_FRIEND_INVITE_ALREADY,
	eRESULT_FAIL_FRIEND_INVITE_ALREADY_BLOCKOUT,
	eRESULT_FAIL_FRIEND_INVITE_ALREADY_BLOCKOUT_OTHER,
	eRESULT_FAIL_FRIEND_INVITE_SELF,
	eRESULT_FAIL_FRIEND_INVITE_RECV_FULL_OTHER,
	eRESULT_FAIL_FRIEND_INVITE_TOTURIALZONE,		
	eRESULT_FAIL_FRIEND_INVITE_PVP,
	eRESULT_FAIL_FRIEND_JOIN,
	eRESULT_FAIL_FRIEND_JOIN_NOT_EXIST_INVITE,
	eRESULT_FAIL_FRINND_JOIN_ALREADY,
	eRESULT_FAIL_FRIEND_JOIN_FULL,
	eRESULT_FAIL_FRIEND_JOIN_FULL_OTHER,
	eRESULT_FAIL_FRIEND_JOIN_ALREADY_BLOCKOUT,
	eRESULT_FAIL_FRIEND_JOIN_ALREADY_BLOCKOUT_OTHER,
	eRESULT_FAIL_FRIEND_JOIN_REFUSE,
	eRESULT_FAIL_FRIEND_DELETE,
	eRESULT_FAIL_FRIEND_HELLO,
	eRESULT_FAIL_FRIEND_HELLO_COOLTIME,
	eRESULT_FAIL_FRIEND_HELLO_MAX_COUNT,
	eRESULT_FAIL_FRIEND_RECALL,
	eRESULT_FAIL_FRIEND_RECALL_COOLTIME,
	eRESULT_FAIL_FRIEND_CONDITION,
	eRESULT_FAIL_FRIEND_CONDITION_FULL,
	eRESULT_FAIL_FRIEND_WARP,
	eRESULT_FAIL_FRIEND_WARP_BUSY,
	eRESULT_FAIL_FRIEND_WARP_COOLTIME,
	eRESULT_FAIL_FRIEND_WARP_NOT_ACTIVE,
	eRESULT_FAIL_FRIEND_WARP_TUTORIALZONE,				
	eRESULT_FAIL_FRIEND_CONNECT_REQUEST,					
	eRESULT_FAIL_FRIEND_CONNECT_REQUEST_ALREADY_CONNECT,			
	eRESULT_FAIL_FRIEND_CONNECT_REQUEST_COOLTIME,				
	//blockout
	eRESULT_FAIL_BLOCKOUT_INSERT,
	eRESULT_FAIL_BLOCKOUT_INSERT_FULL,
	eRESULT_FAIL_BLOCKOUT_INSERT_NOTHING_USER,
	eRESULT_FAIL_BLOCKOUT_INSERT_ARLEADY,
	eRESULT_FAIL_BLOCKOUT_INSERT_ARLEADY_FRIEND,
	eRESULT_FAIL_BLOCKOUT_DELETE,
	eRESULT_FAIL_BLOCKOUT_DELETE_NOTHING_USER,

	//social history registry
	eRESULT_FAIL_HISTORY_REGISTRY,
	eRESULT_FAIL_HISTORY_REGISTRY_FULL,
	eRESULT_FAIL_HISTORY_REGISTRY_ALREADY,

	//game invite
	eRESULT_FAIL_GAME_INVITE,
	eRESULT_FAIL_GAME_INVITE_OVER,
	eRESULT_FAIL_GAME_INVITE_COOLTIME,
	eRESULT_FAIL_GAME_INVITE_REWARD_ALREADY,
	eRESULT_FAIL_GAME_INVITE_NOT_REWARD,

	//weme login
	eRESULT_WEMEALOGIN_USERINFOREQ,
	eRESULT_WEMEALOGIN_NOTUSER,
	eRESULT_WEMEALOGIN_FAIL,
	eRESULT_WEMEALOGIN_BLOCK,
	eRESULT_WEMEALOGIN_BADAUTH,
	eRESULT_WEMEALOGIN_AUTHSERVERDISCONNECT,
	eRESULT_WEMEALOGIN_TMPUSER,

	//iap - apple
	eRESULT_IAP_NOINSERT,
	eRESULT_IAP_NOUSE,
	eRESULT_IAP_COMPLATE,

	//bad packet
	eRESULT_FAIL_COND_ITEMUSE_WARPING,
	eRESULT_FAIL_COND_ITEMUSE_EMPTY,
	eRESULT_FAIL_COND_ITEMUSE_OTHER_CONTENTS,
	eRESULT_FAIL_COND_ITEMUSE_OVER_MAXGOLD,
	eRESULT_FAIL_COND_ITEMUSE_OVER_MAXCASH,
	eRESULT_FAIL_COND_ITEMUSE_FAIL_PRIVATESHOP_CREATE,
	eRESULT_FAIL_COND_ITEMUSE_OVER_MAXCONDITION,

	//recommend
	//eRESULT_FAIL_RECOMMEND_TERM,
	//eRESULT_FAIL_RECOMMEND_INFO,
	//eRESULT_SUCC_RECOMMEND_CANCEL,
	eRESULT_FAIL_RECOMMEND_NOT_EXIST_CHARACTER,
	//eRESULT_FAIL_RECOMMEND_RECEIVE,
	//eRESULT_FAIL_RECOMMEND_RECEIVE_COUNT ,

	//coupon
	eRESULT_FAILE_COUPON_DELAY,
	eRESULT_FAILE_COUPON_DUPLICATE,
	eRESULT_FAILE_COUPON_DAILYOVER,
	eRESULT_FAILE_COUPON_EXPIRATION,
	eRESULT_FAILE_COUPON_DELETED,
	eRESULT_FAILE_COUPON_COUNTOVER,
	eRESULT_FAILE_COUPON_INVALID,

	eRESULT_FAIL_RANK_SYSTEMWAIT,

	// instance dungeon
	eRESULT_FAIL_INDUN_NOTPARTY,
	eRESULT_FAIL_INDUN_OVERMEMBER,
	eRESULT_FAIL_INDUN_LEVEL,
	eRESULT_FAIL_INDUN_NOTEMPTYINDUN,
	eRESULT_FAIL_INDUN_SYSTEMWAIT,
	eRESULT_FAIL_INDUN_CHARACTER_DEATH,
	eRESULT_FAIL_INDUN_NOTCREATED,
	eRESULT_FAIL_INDUN_POSSIBLECONTENT,

	// pvp
	eRESULT_FAIL_ARENAMATCHING_CANNOTREADY,
	eRESULT_FAIL_ARENAMATCHING_CANNOTCANCEL,
	eRESULT_FAIL_ARENAMATCHING_EMPTY,
	eRESULT_FAIL_ARENAMATCHING_SYSTEMFAILURE,
	eRESULT_FAIL_ARENAMATCHING_NOTPARTY,
	eRESULT_FAIL_ARENAMATCHING_LEVEL,
	eRESULT_FAIL_ARENAMATCHING_LIMITCOUNT_ZERO,
	eRESULT_FAIL_ARENAMATCHING_NOTMATCHING,
	eRESULT_FAIL_ARENAMATCHING_ALREADY,
	eRESULT_FAIL_ARENAMATCHING_CANCEL_ALREADYPLAY,
	eRESULT_FAIL_ARENAMATCHING_PLAY,
	eRESULT_FAIL_ARENAMATCHING_PARTYUSERCOUNTOVER,
	eRESULT_FAIL_ARENAMATCHING_NOTOPEN,
#if INTEGRATED_ARENA_MATCHING
	eRESULT_FAIL_ARENAMATCHING_NOTGOINTO,
#endif
	eRESULT_FAIL_ARENAMATCHING_PARTYUSER_LOGOUT,
	eRESULT_FAIL_ARENAMATCHING_OTHER_CONTENTS,
	eRESULT_FAIL_ARENA_OTHER_CONTENTS,
	eRESULT_FAIL_ARENA_FINISHEDGAME,
	eRESULT_NOTIFY_ARENAMATCHING_START,
	eRESULT_NOTIFY_ARENAMATCHING_RESTART,
	eRESULT_NOTIFY_ARENAMATCHING_CENCEL_MEORMYPARTY,
	eRESULT_NOTIFY_ARENAMATCHING_COMPLETE,
	eRESULT_NOTIFY_ARENAMATCHING_GOINTO_YES,
	eRESULT_NOTIFY_ARENAMATCHING_GOINTO_NO,

	//indun matching
	eRESULT_FAIL_INDUNMATCHING_NOTREADY,
	
	//event quest
	eRESULT_FAIL_EVENT_QUEST,
	eRESULT_FAIL_EVENT_QUEST_DISABLE,
	eRESULT_FAIL_EVENT_QUEST_CLEAR,
	
	//rename
	eRESULT_FAIL_CHARACTER_NAME_CHANGE_SYSTEM_ERROR,
	eRESULT_FAIL_CHARACTER_NAME_CHANGE_USE_ALREADY,
	eRESULT_FAIL_GUILD_NAME_CHANGE_SYSTEM_ERROR,
	eRESULT_FAIL_GUILD_NAME_CHANGE_USE_ALREADY,

	eRESULT_FAIL_PET_CALL_ALREADY,						//이미 소환중인 펫이 있음.
	eRESULT_FAIL_PET_EMPTY_SLOT,						//해당 펫 슬롯은 비어 있는 슬롯.
	eRESULT_FAIL_PET_NOT_EXSIT,						//소환중인 펫이 없음.
	eRESULT_FAIL_PET_BAD_TYPE_ITEM,						//장착 불가능한 아이템.
	eRESULT_FAIL_PET_NOT_EQUIP_ITEM,					//장착중인 아이템이 없음.

	eRESULT_FAIL_PET_NEED_CASH,						//캐쉬부족.
	eRESULT_FAIL_PET_NEED_LEVEL,						//레벨부족.
	eRESULT_FAIL_PET_NEED_GOLD,						//골드부족.
	eRESULT_FAIL_PET_MAX_LEVEL,						//이미 최대 레벨.
	eRESULT_FAIL_PET_USE_ITEM_FULL,

	eRESULT_FAIL_PET_USE_ITEM_COMBAT,					//전투중 사용 불가.
	eRESULT_FAIL_PET_USE_ITEM_ZONE,						//해당 지역 사용불가.
	eRESULT_FAIL_PET_HUNGRY_FULL,						//배고픔 풀.
	eRESULT_FAIL_PET_SAME,							//동일한 펫임.
	eRESULT_FAIL_PET_ITEM_COMPOSE,						//펫 합성용 아이템이 아님.

	eRESULT_FAIL_PET_ITEM_COMPOSE_MAX_EXP,					//펫 합성후 경험치가 최대를 넘었음.
	eRESULT_FAIL_PET_FULL_SLOT,						//펫 슬롯 풀.
	
#if INTEGRATED_ARENA_MATCHING
	eRESULT_FAIL_INDUNMATCHING_CANNOTREADY,
	eRESULT_FAIL_INDUNMATCHING_CANNOTCANCEL,
	eRESULT_FAIL_INDUNMATCHING_EMPTY,
	eRESULT_FAIL_INDUNMATCHING_SYSTEMFAILURE,
	eRESULT_FAIL_INDUNMATCHING_NOTPARTY,
	eRESULT_FAIL_INDUNMATCHING_LEVEL,
	eRESULT_FAIL_INDUNMATCHING_LIMITCOUNT_ZERO,
	eRESULT_FAIL_INDUNMATCHING_NOTMATCHING,
	eRESULT_FAIL_INDUNMATCHING_ALREADY,
	eRESULT_FAIL_INDUNMATCHING_CANCEL_ALREADYPLAY,
	eRESULT_FAIL_INDUNMATCHING_PLAY,
	eRESULT_FAIL_INDUNMATCHING_PARTYUSERCOUNTOVER,
	eRESULT_FAIL_INDUNMATCHING_NOTOPEN,
	eRESULT_FAIL_INDUNMATCHING_NOTGOINTO,
	eRESULT_FAIL_INDUNMATCHING_PARTYUSER_LOGOUT,
	eRESULT_FAIL_INDUNMATCHING_OTHER_CONTENTS,
#if INDUN_TIME
	eRESULT_FAIL_INDUNMATCHING_NO_CLEAR_NORMALMODE,
#endif
	eRESULT_FAIL_INDUN_OTHER_CONTENTS,
	eRESULT_FAIL_INDUN_FINISHEDGAME,
	eRESULT_NOTIFY_INDUNMATCHING_START,
	eRESULT_NOTIFY_INDUNMATCHING_RESTART,
	eRESULT_NOTIFY_INDUNMATCHING_CENCEL_MEORMYPARTY,
	eRESULT_NOTIFY_INDUNMATCHING_COMPLETE,
	eRESULT_NOTIFY_INDUNMATCHING_GOINTO_YES,
	eRESULT_NOTIFY_INDUNMATCHING_GOINTO_NO,
	eRESULT_FAIL_INDUN_ALREADYREWARDITEMGET,
	eRESULT_FAIL_INDUN_SYSTEMFAILURE,
	eRESULT_FAIL_INDUN_FULL_INVEN,
#endif

	eRESULT_MAX
};

public enum eBUFFTYPE : int
{
	eBUFFTYPE_NOTHING = 0,
	
	eBUFFTYPE_PHYSICAL_ATTACK_CONTROL_ADDPROB,
	eBUFFTYPE_MIN_PHYSICAL_ATTACK_CONTROL_ADDPROB,
	eBUFFTYPE_MAX_PHYSICAL_ATTACK_CONTROL_ADDPROB,
	
	eBUFFTYPE_MAGICAL_ATTACK_CONTROL_ADDPROB,
	eBUFFTYPE_MIN_MAGICAL_ATTACK_CONTROL_ADDPROB,
	eBUFFTYPE_MAX_MAGICAL_ATTACK_CONTROL_ADDPROB,
	
	eBUFFTYPE_PHYSICAL_RECEIVE_DAMAGE_CONTROL_ADDPROB,
	eBUFFTYPE_MAGICAL_RECEIVE_DAMAGE_CONTROL_ADDPROB,
	eBUFFTYPE_TOTAL_RECEIVE_DAMAGE_CONTROL_ADDPROB,
	
	eBUFFTYPE_SHIELD_DEFENSE_ADDPROB,
	
	eBUFFTYPE_PHYSICAL_DEFENSE_CONTROL_ADDPROB,
	
	eBUFFTYPE_MAGICAL_RESIST_CONTROL_ADDPROB,
	
	eBUFFTYPE_CUR_HP_CONTROL_ADDPROB,
	eBUFFTYPE_CUR_MP_CONTROL_ADDPROB,
	
	eBUFFTYPE_TOTAL_HP_CONTROL_ADDPROB,
	eBUFFTYPE_TOTAL_MP_CONTROL_ADDPROB,
	
	eBUFFTYPE_HP_CHARGE_CONTROL_ADDPROB,
	eBUFFTYPE_MP_CHARGE_CONTROL_ADDPROB,
	
	eBUFFTYPE_PHYSICAL_REFLECTION_PROB,
	eBUFFTYPE_MAGICAL_REFLECTION_PROB,
	eBUFFTYPE_REFLECTION_ADD,
	
	eBUFFTYPE_DEBUFF_TIME_CONTROL_ADDPROB,
	
	eBUFFTYPE_AGGRO_ACCRUE_CONTROL_ADDPROB,
	
	eBUFFTYPE_STUN_NOTHING,
	
	eBUFFTYPE_POISON_ADDPROB,
	
	eBUFFTYPE_BLEEDING_ADDPROB,
	
	eBUFFTYPE_HP_DRAIN_ADDPROB,
	
	eBUFFTYPE_DODGE_CONTROL_PROB,
	eBUFFTYPE_CRITICAL_CONTROL_PROB,
	eBUFFTYPE_CRITICAL_DAMAGE_CONTROL_PROB,
	
	eBUFFTYPE_ACCURACY_CONTROL_PROB,
	eBUFFTYPE_MOVESPEED_CONTROL_PROB,
	eBUFFTYPE_ATTSPEED_CONTROL_PROB,
	
	eBUFFTYPE_BURNING_ADDPROB,
	
	eBUFFTYPE_BIND_NOTHING,
	
	eBUFFTYPE_MANA_SPEND_CONTROL_ADDPROB,
	
	eBUFFTYPE_COOLTIME_CONTROL_ADDPROB,
	
	eBUFFTYPE_HEAL_ADDPROB,
	eBUFFTYPE_HEAL_DIVIDE_PROB,
	
	eBUFFTYPE_LIMIT_SHIELD_ADDPROB,
	
	eBUFFTYPE_BLIND_PROB,
	
	eBUFFTYPE_RECV_DAMAGE_TARGET_CHANGE_PROB,
	
	eBUFFTYPE_AGGRO_TARGET_CHANGE_PROB,
	
	eBUFFTYPE_RECV_DAMAGE_TO_MP_PROB,
	
	eBUFFTYPE_HP_CONTROL_DURATION_ADDPROB,
	
	eBUFFTYPE_ADD_MAGIC_DAMAGE_ADDPROB,
	
	eBUFFTYPE_DEBUFF_RESIST_PROB,
	
	eBUFFTYPE_FREEZE_PROB,
	
	eBUFFTYPE_SLEEP_PROB,
	
	eBUFFTYPE_EXP_CONTROL_PROB,
	
	eBUFFTYPE_BATTLE_EXP_CONTROL_PROB,
	
	eBUFFTYPE_SLOW_PROB,
	
	eBUFFTYPE_BATTLE_GOLD_CONTROL_PROB,
	eBUFFTYPE_BATTLE_ITEMDROP_CONTROL_PROB,
	
	eBUFFTYPE_RECV_CUR_HP_INCREASE_CONTROL_PROB,
	
	eBUFFTYPE_CONDITION_BATTLE_EXP_CONTROL_PROB,
	
	eBUFFTYPE_SIZE_CONTROL_PROB,
	
	eBUFFTYPE_HP_INSTEAD_MP_PROB,
	
	eBUFFTYPE_CUR_HP_COUNTDOWN_CONTROL_ADDPROB,
	
	eBUFFTYPE_SKILL_DISTANCE_CONTROL_ADDPROB,
	
	eBUFFTYPE_FEAR_NOTHING,
	
	eBUFFTYPE_ATTACK_STACK_TO_CRITICAL_ADDPROB,
	eBUFFTYPE_DAMAGE_STACK_TO_DODGE_ADDPROB,
	
	eBUFFTYPE_GOAL_ATTACK_STACK_CONTROL_ADD,
	eBUFFTYPE_GOAL_DAMAGE_STACK_CONTROL_ADD,
	
	eBUFFTYPE_BLANK_NOTHING,
	
	eBUFFTYPE_AIRBON_NOTHING,
	eBUFFTYPE_TRANSFORM_ADD,
	eBUFFTYPE_GRAY_NOTHING,
	
	eBUFFTYPE_STUN_RESIST_PROB,
	eBUFFTYPE_BURNNING_RESIST_PROB,
	eBUFFTYPE_FREEZE_RESIST_PROB,
	eBUFFTYPE_BLEEDING_RESIST_PROB,
	eBUFFTYPE_BLIND_RESIST_PROB,
	eBUFFTYPE_HOLD_RESIST_PROB,
	eBUFFTYPE_POISON_RESIST_PROB,
	eBUFFTYPE_SLEEP_RESIST_PROB,
	eBUFFTYPE_SLOW_RESIST_PROB,
	eBUFFTYPE_MOVE_RESIST_PROB,
	eBUFFTYPE_FEAR_RESIST_PROB,
	eBUFFTYPE_BLANK_RESIST_PROB,
	eBUFFTYPE_AIRBONE_RESIST_PROB,
	eBUFFTYPE_TRANSFORM_RESIST_PROB,
	eBUFFTYPE_GRAY_RESIST_PROB,

#if INDUN_COUNT_ITEM
	eBUFFTYPE_NORMALHARDPLAYCOUNT_ADD,
	eBUFFTYPE_HELLPLAYCOUNT_ADD,
	eBUFFTYPE_HELLPLAYCOUNTALL_ADD,
#endif
	
	//!! 주의 : 제일 아래에 놓여야 한다.
	//Moment 이지만 예외처리로 디버프 저항 처리를 위해서 넣음
	eBUFFTYPE_MOVE_ADD,
	eBUFFTYPE_POINT_MOVE_ADD,
	
	eBUFFTYPE_MAX
	
	// add soon
//	eBUFFTYPE_BLANK,
};

#if false
public enum eBUFFTYPE : int
{
	eBUFFTYPE_NOTHING = 0,
	
	eBUFFTYPE_ATTACK_PLUS,
	eBUFFTYPE_DEFENSE_PLUS,
	eBUFFTYPE_MOVESPEED_PLUS,
	
	eBUFFTYPE_ATTACK_PERCENT,
	eBUFFTYPE_DEFENSE_PERCENT,
	eBUFFTYPE_MOVESPEED_PERCENT,
	
	eBUFFTYPE_STUN,
	
	eBUFFTYPE_MAX
};
#endif

#region -ChannelList
public enum eCONFUSIONTYPE : int
{
	eCONFUSION_NOTHING = 0,

	eCONFUSION_NORMAL,
	eCONFUSION_BUSY,
	eCONFUSION_SATURATION,

	eCONFUSION_INSPECTION,

	eCONFUSION_MAX
};
#endregion

public enum eQUICKSLOT_TYPE : int
{
	eQUICKSLOT_TYPE_NOTHING = 0,

	eQUICKSLOT_TYPE_ITEM,
	eQUICKSLOT_TYPE_SKILL,

	eQUICKSLOT_TYPE_MAX
};

public enum eITEM_OPTION : int
{
	eITEM_OPTION_NOTHING = 0,

	eITEM_OPTION_HP_PLUS,
	eITEM_OPTION_MP_PLUS,

	eITEM_OPTION_PATK_DMG_MIN,
	eITEM_OPTION_PATK_DMG_MAX,
	eITEM_OPTION_PATK_DMG,

	eITEM_OPTION_ATK_HIT_PROB,
	eITEM_OPTION_CRITICAL_PROB,

	eITEM_OPTION_MATK_DMG_MIN,
	eITEM_OPTION_MATK_DMG_MAX,
	eITEM_OPTION_MATK_DMG,

	eITEM_OPTION_PDEF,
	eITEM_OPTION_MDEF,

	eITEM_OPTION_DODGE_PROB,

	eITEM_OPTION_FIRE,
	eITEM_OPTION_ICE,
	eITEM_OPTION_LIGHT,
	eITEM_OPTION_DARK,
	eITEM_OPTION_NATURE,

	eITEM_OPTION_CRI_DMG,

	eITEM_OPTION_STUN_IMMUNE,
	eITEM_OPTION_BLEED_IMMUNE,

	eITEM_OPTION_NORAML_DMG_PROB,
	eITEM_OPTION_ELITE_DMG_PROB,
	eITEM_OPTION_BOSS_DMB_PROB,

	eITEM_OPTION_NORMAL_CRI_DMG_PROB,
	eITEM_OPTION_ELITE_CRI_DMG_PROB,
	eITEM_OPTION_BOSS_CRI_DMG_PROB,

	eITEM_OPTION_NORM_DEF_PROB,
	eITEM_OPTION_ELITE_DEF_PROB,
	eITEM_OPTION_BOSS_DEF_PROB,

	eITEM_OPTION_NORMAL_CRI_PROB,
	eITEM_OPTION_ELITE_CRI_PROB,
	eITEM_OPTION_BOSS_CRI_PROB,

	eITEM_OPTION_HP_REGEN,
	eITEM_OPTION_MP_REGEN,

	eITEM_OPTION_PATK_PROB,
	eITEM_OPTION_MATK_PROB,

	eITEM_OPTION_HP_DRAIN,
	eITEM_OPTION_HP_DRAIN_PROB,

	eITEM_OPTION_HP_PROB,
	eITEM_OPTION_MP_PROB,

	eITEM_OPTION_PDEF_PROB,
	eITEM_OPTION_MDEF_PROB,

	eITEM_OPTION_HP_REGEN_PROB,
	eITEM_OPTION_MP_REGEN_PROB,

	eITEM_OPTION_ATK_SPEED_PROB,
	eITEM_OPTION_MOVE_SPEED_PROB,

	eITEM_OPTION_MAX
};

public enum eATTRIBUTE_TYPE
{
	eATTRIBUTE_FIRE = 0,
	eATTRIBUTE_ICE,
	eATTRIBUTE_LIGHT,
	eATTRIBUTE_DARK,
	eATTRIBUTE_NATURE,

	eATTRIBUTE_MAX
}

public enum eCHANGE_INFO_TYPE
{
	eCHANGE_INFO_NOTHING = 0,

	eCHANGE_INFO_HP_MAX,
	eCHANGE_INFO_MP_MAX,

	eCHANGE_INFO_PHYSIC_DMGMIN,
	eCHANGE_INFO_PHYSIC_DMGMAX,

	eCHANGE_INFO_MAGIC_DMGMIN,
	eCHANGE_INFO_MAGIC_DMGMAX,

	eCHANGE_INFO_PHYSIC_DEF,
	eCHANGE_INFO_MAGIC_DEF,

	eCHANGE_INFO_CRITICAL_PROB,
	eCHANGE_INFO_ACCURACY_PROB,
	eCHANGE_IFNO_DODGE_PROB,

	eCHANGE_INFO_MOVE_SPEED,
	eCHANGE_INFO_ATTACK_SPEED,

	eCHANGE_INFO_HP_REGEN,
	eCHANGE_INFO_MP_REGEN,

	eCHANGE_INFO_PHYSIC_DMG_DEC,
	eCHANGE_INFO_MAGIC_DMG_DEC,

	eCHANGE_INFO_MAX
}

public enum eITEM_ENCHANT_TYPE : int
{
	eITEM_ENCHANT_TYPE_NORMAL = 0,
	eITEM_ENCHANT_TYPE_STRENGTHEN = 1,
	eITEM_ENCHANT_TYPE_CASH = 2,
};


public enum eITEM_STRENGTHEN_TYPE : int
{
	eITEM_STRENGTHEN_TYPE_NONE	= 0,

	eITEM_STRENGTHEN_TYPE_START,
	eITEM_STRENGTHEN_TYPE_CANCEL,
	eITEM_STRENGTHEN_TYPE_END,

	eITEM_STRENGTHEN_TYPE_MAX = 4,
};


enum eUSEREVENTTYPE : int
{
	eUSEREVENTTYPE_NOTHING = 0,

	eUSEREVENTTYPE_ITEM,
	eUSEREVENTTYPE_ARENA,

	eUSEREVENTTYPE_MAX
};

enum eUSEREVENT_ITEM_GETTYPE : int
{
	eUSEREVENT_ITEM_GETTYPE_NOTHING = 0,

	eUSEREVENT_ITEM_GETTYPE_HUNTING,
	eUSEREVENT_ITEM_GETTYPE_MIX,
	eUSEREVENT_ITEM_GETTYPE_RANDOMBOX,
	eUSEREVENT_ITEM_GETTYPE_COLLECTING,
	eUSEREVENT_ITEM_GETTYPE_PRODUCT,
	eUSEREVENT_ITEM_GETTYPE_STRENGTHEN,
	eUSEREVENT_ITEM_GETTYPE_RULLET,

	eUSEREVENT_ITEM_GETTYPE_MAX
};

enum eUSEREVENT_ARENATYPE
{
	eUSEREVENT_ARENATYPE_NOTHING = 0,
	
	eUSEREVENT_ARENATYPE_TIMEOUT_ENTERING,
	eUSEREVENT_ARENATYPE_LEAVE,
	eUSEREVENT_ARENATYPE_DEATH,
	
	eUSEREVENT_ARENATYPE_MAX
};

#if false
public class _category : AsBaseClass
{
	public ushort m_ProtocolCount;
	public int m_ProtocolSize;

	public _category()
	{
		m_ProtocolCount = 0;
		m_ProtocolSize = 0;
	}
};
#endif

public enum eITEM_PRODUCT_TECHNIQUE_TYPE : int
{
#if OLD_PRODUCT
	WEAPON,
	ARMOR,
	ACCESSORY,
#else
	RING,
	NECKLACE,
	EARRING,	
#endif
	POTION,

	MINERAL,
	PLANTS,
	SPIRIT,
	QUEST,

	eITEM_PRODUCT_TECHNIQUE_MAX = QUEST,
};


public enum eITEMCHANGECONTENTS : int
{
	eITEMCHANGECONTENTS_NOTHING = 0,

	eITEMCHANGECONTENTS_LOADING,
	eITEMCHANGECONTENTS_ITEMMOVE,
	eITEMCHANGECONTENTS_SORT,
	eITEMCHANGECONTENTS_PICKUP,
	eITEMCHANGECONTENTS_STRENGTHEN,
	eITEMCHANGECONTENTS_ENCHANT,
	eITEMCHANGECONTENTS_TRADE,
	eITEMCHANGECONTENTS_POST,
	eITEMCHANGECONTENTS_RANDITEM,
	eITEMCHANGECONTENTS_MIXITEM,
	eITEMCHANGECONTENTS_QUEST,
	eITEMCHANGECONTENTS_CHEAT,
	eITEMCHANGECONTENTS_SHOP,
	eITEMCHANGECONTENTS_PRIVATESHOP,
	eITEMCHANGECONTENTS_PRODUCT,
	eITEMCHANGECONTENTS_CASHSHOP,
	eITEMCHANGECONTENTS_SOCIALSHOP,
	eITEMCHANGECONTENTS_ROULETTE,
	eITEMCHANGECONTENTS_ACTION,

	eITEMCHANGECONTENTS_SHOP_PAY,
	eITEMCHANGECONTENTS_EVENT_BOX,
	eITEMCHANGECONTENTS_LEVLE_COMPLETE,
    eITEMCHANGECONTENTS_QUEST_COMPLETE_REWARD,

	eITEMCHANGECONTENTS_MAX
};

public enum eSTORAGE_MOVE_TYPE : int
{
	eSTORAGE_MOVE_TYPE_NONE = 0,

	eSTORAGE_MOVE_TYPE_INSIDE,

	eSTORAGE_MOVE_TYPE_DRAG_INPUT,
	eSTORAGE_MOVE_TYPE_INPUT,

	eSTORAGE_MOVE_TYPE_DRAG_OUTPUT,
	eSTORAGE_MOVE_TYPE_OUTPUT,

	eSTORAGE_MOVE_TYPE_REMOVE
}

#region -Guild
public enum eGUILDPERMISSION : int
{
	eGUILDPERMISSION_NOTHING = 0,	// 00000000

	eGUILDPERMISSION_NOTICE = 1,	// 00000001
	eGUILDPERMISSION_PUBLICIZE = 2,	// 00000010
	eGUILDPERMISSION_INVITE = 4,	// 00000100
	eGUILDPERMISSION_EXILE = 8,		// 00001000
	eGUILDPERMISSION_DEPOSIT = 16,	// 00010000
	eGUILDPERMISSION_WITHDRAW = 32,	// 00100000
	eGUILDPERMISSION_AUTHORIZE = 64,// 01000000

	eGUILDPERMISSION_BASE = eGUILDPERMISSION_DEPOSIT,
	eGUILDPERMISSION_ALL = eGUILDPERMISSION_NOTICE
						+ eGUILDPERMISSION_PUBLICIZE
						+ eGUILDPERMISSION_INVITE
						+ eGUILDPERMISSION_EXILE
						+ eGUILDPERMISSION_DEPOSIT
						+ eGUILDPERMISSION_WITHDRAW
						+ eGUILDPERMISSION_AUTHORIZE
}

public enum eGUILDJOINTYPE : int
{
	eGUILDJOINTYPE_NOTHING = 0,

	eGUILDJOINTYPE_ACCEPT,
	eGUILDJOINTYPE_REFUSE,
	eGUILDJOINTYPE_APPROVE,
	eGUILDJOINTYPE_NOT_APPROVE,

	eGUILDJOINTYPE_MAX
}

public enum eGUILDMEMBER_DELETE : int
{
	eGUILDMEMBER_DELETE_NOTHING	= 0,

	eGUILDMEMBER_DELETE_EXIT,
	eGUILDMEMBER_DELETE_EXILE,

	eGUILDMEMBER_DELETE_MAX
}

public enum eGUILD_UI_SCROLL : int
{
	eGUILD_UI_SCROLL_NOTHING = 0,

	eGUILD_UI_SCROLL_GUILD,
	eGUILD_UI_SCROLL_APPROVE_MEMBER,
	eGUILD_UI_SCROLL_NOT_APPROVE_MEMBER,

	eGUILD_UI_SCROLL_MAX
}
#endregion

#region -social
public enum eFRIEND_JOIN_TYPE
{
	eFRIEND_JOIN_NOTHING = 0,

	eFRIEND_JOIN_ACCEPT,
	eFRIEND_JOIN_REFUSE,
	eFRIEND_JOIN_BUSY,

	eFRIEND_JOIN_MAX
};
public enum eSOCIAL_UI_TYPE : int
{
	eSOCIAL_UI_NOTHING = 0,

	eSOCIAL_UI_HISTORY,
	eSOCIAL_UI_FRIEND,
	eSOCIAL_UI_BLOCK,
	eSOCIAL_UI_FRIEND_RANDOM,
	eSOCIAL_UI_FRIEND_APPLY,
	eSOCIAL_UI_RECOMMEND,

	eSOCIAL_UI_TYPE_MAX

};

public enum eFRIEND_BUTTON_TYPE : int
{
	eFRIEND_BUTTON_NOTHING = 0,

	eFRIEND_BUTTON_HELLO_ENABLE = 1,		//0x0001
	eFRIEND_BUTTON_HELLO_DISABLE = 2,		//0x0002
	eFRIEND_BUTTON_HELLO_RECV = 4,			//0x0004
	eFRIEND_BUTTON_RECALL_ENABLE = 8,		//0x0008
	eFRIEND_BUTTON_RECALL_DISABLE = 16,		//0x0010
	eFRIEND_BUTTON_CONDITION_ENABLE = 32,	//0x0020

	eFRIEND_BUTTON_BASE = eFRIEND_BUTTON_HELLO_ENABLE,

	eFRIEND_BUTTON_MAX

};

public enum eSOCIAL_HISTORY_PLATFORM : int
{
	eSOCIAL_HISTORY_PLATFORM_NOTHING = 0,

	eSOCIAL_HISTORY_PLATFORM_FACEBOOK = 1,
	eSOCIAL_HISTORY_PLATFORM_TWITTER = 2,

	eSOCIAL_HISTORY_PLATFORM_ALL = 100
};
#endregion  -social

public enum eCOLLECT_STATE : int
{
	eCOLLECT_STATE_START,
	eCOLLECT_STATE_CANCEL,
	eCOLLECT_STATE_COMPLETE,

	eCOLLECT_STATE_MAX
};

public enum eOTHER_INFO_TYPE : int
{
	eOTHER_INFO_TYPE_NOTHING  = 0,

	eOTHER_INFO_TYPE_PLAYER,
	eOTHER_INFO_TYPE_GUILD_MEMBER,
	eOTHER_INFO_TYPE_SOCIAL_FRIEND,
	eOTHER_INFO_TYPE_RANK,

	eOTHER_INFO_TYPE_MAX
};

public enum eOSTYPE : int
{
	eOSTYPE_NOTHING = 0,

	eOSTYPE_APPLE,
	eOSTYPE_ANDROID,

	eOSTYPE_MAX
};

#region -Condition
public enum eCONDITION_TYPE : int
{
	eCONDITION_TYPE_NOTHING = 0,
	eCONDITION_TYPE_SYNC,
	eCONDITION_TYPE_DAILY_FILLUP,
	eCONDITION_TYPE_ADD,
	eCONDITION_TYPE_MAX
};
#endregion

#region -EventStart
public enum eEVENT_TYPE : int
{
	eEVENT_TYPE_NOTHING = 0,

	eEVENT_TYPE_TIME_EXP,
	eEVENT_TYPE_TIME_GOLD,
	eEVENT_TYPE_TIME_DROP,
	eEVENT_TYPE_TIME_REWARD,
	eEVENT_TYPE_TIME_CONDITION,

	eEVENT_TYPE_ATTEND_ADD_REWARD,
	eEVENT_TYPE_RETURN_ADD_REWARD,

	eEVENT_TYPE_ITEM_STRENGTHEN,

	eEVENT_TYPE_COMBINE_COLLECT,
	eEVENT_TYPE_COMBINE_PRODUCT,
	eEVENT_TYPE_COMBINE_MIX,
	eEVENT_TYPE_COMBINE_COMMISSION,
	eEVENT_TYPE_COMBINE_MOB_REGEN,
	eEVENT_TYPE_COMBINE_CONDITION_DROP,

	eEVENT_TYPE_GACHA_GRADE_RATE,

	eEVENT_TYPE_MAX

//	eEVENT_TYPE_INVITE_ADD_REWARD,
//	eEVENT_TYPE_NPC_SHOP,
//	eEVENT_TYPE_QUEST,
};
#endregion


public enum ePRODUCTCONTENTS : int
{
	ePRODUCTCONTENTS_NOTHING = 0,

	ePRODUCTCONTENTS_TECHNIQUE,
	ePRODUCTCONTENTS_REGISTER,
	ePRODUCTCONTENTS_COMPLETE,
	ePRODUCTCONTENTS_CANCEL,
	ePRODUCTCONTENTS_RECEIVE,
	ePRODUCTCONTENTS_COLLECT,

	ePRODUCTCONTENTS_CASH_DIRECT,
	ePRODUCTCONTENTS_CASH_SLOT,
	ePRODUCTCONTENTS_CASH_TECHNIQUE,
	ePRODUCTCONTENTS_CASH_LEVEL_UP,

	ePRODUCTCONTENTS_MAX
};

public enum eLOGINTYPE : int
{
	eLOGINTYPE_NOTHING = 0,

	eLOGINTYPE_WEME,
	eLOGINTYPE_FACEBOOK,
	
	eLOGINTYPE_GOOGLEPLUS, //2014.2.14.
    eLOGINTYPE_NAVER,   //2014.2.14.
	eLOGINTYPE_NAVER_BAND,
	eLOGINTYPE_DEVICE,
	eLOGINTYPE_YAHOOJP,
	eLOGINTYPE_TWITTER,
	eLOGINTYPE_MAX
};

public enum eGAME_INVITE_PLATFORM : int
{
	eGAME_INVITE_PLATFORM_NOTHING = 0,

	eGAME_INVITE_PLATFORM_FACEBOOK,
	eGAME_INVITE_PLATFORM_KAKAOTALK,
	eGAME_INVITE_PLATFORM_SMS,
	eGAME_INVITE_PLATFORM_BAND,
	
	eGAME_INVITE_PLATFORM_LOBI,			//<<추가 2014.09.19.
	eGAME_INVITE_PLATFORM_LINE,			//<<추가 2014.09.19.
	eGAME_INVITE_PLATFORM_TWITTER,
	
	eGAME_INVITE_PLATFORM_ALL,			//저장시사용  2014.09.19.
	eGAME_INVITE_PLATFORM_MAX
}

enum eITEM_MIX_TYPE : int
{
	eITEM_MIX_TYPE_NONE		= 0,

	eITEM_MIX_TYPE_DECOMPOSITION,	
	eITEM_MIX_TYPE_EQUIP_OPT,	
	eITEM_MIX_TYPE_SOUL_STONE,	
	eITEM_MIX_TYPE_COSTUME,		

	eITEM_MIX_TYPE_MAX
};